buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.5.2"
    }
}

allprojects {
    apply plugin: "eclipse"
    apply plugin: "idea"

    version = "1.0"
    ext {
        appName = "dashproject"
        gdxVersion = "1.12.1"
    }

    repositories {
        mavenCentral()
        google()
    }
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
    }
}

tasks.eclipse.doLast {
    delete ".project"
}
